### ISSUE TITLE
Compatibility with Windows (10)

### ISSUE THREAD

**Issue by jakejdavis** [ragingwind/devdogs#23]
I just tested this out on Windows 10 and it seems to be compatible apart from the command to show the window.
![capture](https://cloud.githubusercontent.com/assets/11355096/21728580/dd39584a-d43e-11e6-9ec1-6ded1baae826.PNG)

**Comment by ragingwind** [comment]
Thanks for reporting. Unfortunately, I have no Windows machine to maintain this simple tools. I recommend that every user on Windows or Linux should build own version with source.
