### ISSUE TITLE
Move the selection of light/dark theme to the menubar

### ISSUE THREAD

**Issue by sindresorhus** [ragingwind/devdogs#5]
Would clean up the UI. You can hide it with CSS overrides and trigger it with JS.

Example:
https://github.com/sindresorhus/caprine/blob/master/browser.js
https://github.com/sindresorhus/caprine/blob/master/browser.css

**Comment by ragingwind** [comment]
Good idea. and I could change the action of other buttons

**Comment by ragingwind** [comment]
https://github.com/ragingwind/devdogs/commit/6de004d118de4555a6b91d90f35c13ea36a9ce2a
