### ISSUE TITLE
Rename repo to `devdogs`

### ISSUE THREAD

**Issue by sindresorhus** [ragingwind/devdogs#7]
I don't see any point in prefixing it with Electron. It's built with Electron, true, but its it's own product. Same with the header in the readme.

**Comment by ragingwind** [comment]
It's just for me. I prefer to using prefix on a repo to manage a project. I will rename as your opinion.

**Comment by sindresorhus** [comment]
I guess it makes sense if you create node modules or jquery plugins, but this is a standalone product. To be completely correct in that case, it should have been `electron-node-chrome-devdogs` :p

**Comment by ragingwind** [comment]
I agree with you. so I've changed the name. It's not a part of electron like `electron-debug`
