### ISSUE TITLE
Link up DevDocs in the readme

### ISSUE THREAD

**Issue by sindresorhus** [ragingwind/devdogs#8]
I had no idea what it is before Googling it.

**Comment by ragingwind** [comment]
Because you don't need it? :) I will

**Comment by sindresorhus** [comment]
Well, I wouldn't know if I needed it or not, since I don't know what it is. I Googled it, but most would be too lazy and just leave.

**Comment by ragingwind** [comment]
done, https://github.com/ragingwind/devdogs/commit/080c02ed6e7a0a1c76723301c9e258c47b630188
