### ISSUE TITLE
Getting Error on Windows whenever Quit is clicked from menu

### ISSUE THREAD

**Issue by louy2** [ragingwind/devdogs#9]
Trying to get devdogs running on Windows, and found this error in terminal whenever I click "Quit". 

```
[6XXX:1XXX/1XXXX2:ERROR:ipc_channel_win.cc(435)] pipe error: 232
```

But the program still quits as expected, and using keyboard shortcut to quit doesn't show the error.

**Comment by ragingwind** [comment]
described in readme, doesn't support Windows
